### ISSUE TITLE
Wrong devcontainer configuration name

### ISSUE THREAD

**Issue by DevKoenv** [marcosgomesneto/bun-devcontainers#25]
Currently when using the `bun-mariadb` devcontainer configuration the default name is set to `PHP & MariaDB` as you can see [here](https://github.com/marcosgomesneto/bun-devcontainers/blob/main/src/bun-mariadb/.devcontainer/devcontainer.json#L4C1-L4C26)

I'm guessing that this is supposed to be `Bun & MariaDB`

**Comment by marcosgomesneto** [comment]
Hello, thank you very much for your report, I will fix it.
